### PR TITLE
Fix moving in portrait

### LINKED ISSUE #1: arrow keys & orientation
When using plaan vertically, arrow keys listeners and buttons are inversed `¯\_(ツ)_/¯`.

### PR DESCRIPTION
**Pull request by NeeEoo**
Fixes #1.

### CODE REVIEW

File: src/js/script.js [hunk 1]
```diff
@@ -116,17 +116,31 @@
...
+          const isPortrait = matchMedia('screen and (orientation: portrait)').matches;
+          let control      = arrow.dataset.controls;
+
+          if (isPortrait) {
+            if (control.slice(-1) === 'x') {
+              control = control.slice(0, -1) + 'y';
+            } else {
+              control = control.slice(0, -1) + 'x';
+            }
+          }
```
Comment (ffoodd) [inline src/js/script.js]: This part might be slightly shorter I think:

```javascript
if (isPortrait) {
    const axis = (control.slice(-1) === 'x') ? 'y' : 'x';
    control = control.slice(0, -1) + axis;
}
```
 But it requires to use a ternary operator, so it’s up to you — but I can see you're using it above :)

I'll test this and could merge if that works ;)

Comment (NeeEoo) [reply src/js/script.js]: Looks much better and, I just tested it and, it still works. Thank you.

**Comment by ffoodd** [comment]
LGTM, let's merge!

Thanks, and you're welcome if you want to improve anything else ;)
